name: new workflow

on: [push]

jobs:
  run-github-flows:
    runs-on: ubuntu-latest
    steps:
      -  name: list files
         run: |
           pwd
           ls
           node -v
           df -h
      -  name: actions
         id: greet
         uses: actions/hello-world-javascript-action@v1
         with:
           who-to-greet: 'Manikanta and ujwala'
      -  name: output actions
         run: echo "${{ steps.greet.outputs.time }}"