name: first code yml

on: [push]

jobs:
  my first code:
    runs-on: ubuntu-latest
    steps: 
      -  name: my first job
          run: ls -ltr
      -  name: multistage
          run : |
            uname
            node -v
            echo "helo github"  
